// src/lib/players-data.tsx

export interface PlayerStats {
  name: string;
  role: string;
  age: number;
  rating?: number;
  trophies: number;
  majors: number;
  maps?: number;
  team_name: string;
  team_rank: number;
  region: string;
  popularity: number;
  trophies_s: number;
  trophies_a: number;
  tactics?: number;
  development?: number;
  trophies_last_3_years?: number;
  teamLogo: string;
  
  // Добавляем флаг бенча:
  is_bench?: boolean; 
}

export const playersData: PlayerStats[] = [


  {
    "name": "apEX",
    "role": "IGL",
    "age": 33,
    "rating": 0.98,
    "trophies": 41,
    "majors": 22,
    "maps": 2657,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.60,
    "trophies_s": 8,
    "trophies_a": 33,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "ropz",
    "role": "Rifler",
    "age": 26,
    "rating": 1.14,
    "trophies": 35,
    "majors": 13,
    "maps": 1859,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.70,
    "trophies_s": 7,
    "trophies_a": 28,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "ZywOo",
    "role": "AWP",
    "age": 25,
    "rating": 1.39,
    "trophies": 29,
    "majors": 11,
    "maps": 1671,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.95,
    "trophies_s": 7,
    "trophies_a": 22,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "flameZ",
    "role": "Rifler",
    "age": 23,
    "rating": 1.18,
    "trophies": 20,
    "majors": 7,
    "maps": 1057,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 6,
    "trophies_a": 14,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "mezii",
    "role": "Rifler",
    "age": 27,
    "rating": 1.03,
    "trophies": 19,
    "majors": 7,
    "maps": 1168,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 6,
    "trophies_a": 13,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "XTQZZZ",
    "role": "Coach",
    "age": 37,
    "trophies": 23,
    "majors": 9,
    "team_name": "Vitality",
    "team_rank": 1,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 6,
    "trophies_a": 17,
    "trophies_last_3_years": 17,
    "tactics": 2,
    "development": 0,
    "teamLogo": "/images/vitality-logo.webp"
  },
  {
    "name": "karrigan",
    "role": "IGL",
    "age": 36,
    "rating": 0.73,
    "trophies": 27,
    "majors": 22,
    "maps": 2267,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.70,
    "trophies_s": 4,
    "trophies_a": 23,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "NiKo",
    "role": "Rifler",
    "age": 29,
    "rating": 1.12,
    "trophies": 19,
    "majors": 17,
    "maps": 2311,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.70,
    "trophies_s": 5,
    "trophies_a": 14,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "TeSeS",
    "role": "Rifler",
    "age": 25,
    "rating": 1.03,
    "trophies": 8,
    "majors": 9,
    "maps": 1566,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 1,
    "trophies_a": 7,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "m0NESY",
    "role": "AWP",
    "age": 21,
    "rating": 1.26,
    "trophies": 7,
    "majors": 7,
    "maps": 927,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.80,
    "trophies_s": 5,
    "trophies_a": 2,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "kyousuke",
    "role": "Rifler",
    "age": 18,
    "rating": 1.17,
    "trophies": 1,
    "majors": 2,
    "maps": 431,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.55,
    "trophies_s": 1,
    "trophies_a": 0,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "zonic",
    "role": "Coach",
    "age": 39,
    "trophies": 28,
    "majors": 16,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 7,
    "trophies_a": 21,
    "trophies_last_3_years": 2,
    "tactics": 1,
    "development": 0,
    "teamLogo": "/images/falcons-logo.webp"
  },
  {
    "name": "kyxsan",
    "role": "IGL",
    "age": 26,
    "rating": 0.94,
    "trophies": 1,
    "majors": 5,
    "maps": 1198,
    "team_name": "Falcons",
    "team_rank": 2,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/falcons-logo.webp",
    "is_bench": true
  },
  {
    "name": "sh1ro",
    "role": "AWP",
    "age": 24,
    "rating": 1.18,
    "trophies": 17,
    "majors": 8,
    "maps": 1478,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.60,
    "trophies_s": 4,
    "trophies_a": 13,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "magixx",
    "role": "IGL",
    "age": 23,
    "rating": 1.00,
    "trophies": 8,
    "majors": 7,
    "maps": 1181,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 2,
    "trophies_a": 6,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "tN1R",
    "role": "Rifler",
    "age": 25,
    "rating": 1.05,
    "trophies": 1,
    "majors": 3,
    "maps": 945,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "zont1x",
    "role": "Rifler",
    "age": 20,
    "rating": 0.98,
    "trophies": 10,
    "majors": 4,
    "maps": 830,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 3,
    "trophies_a": 7,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "donk",
    "role": "Rifler",
    "age": 19,
    "rating": 1.42,
    "trophies": 10,
    "majors": 5,
    "maps": 757,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.90,
    "trophies_s": 3,
    "trophies_a": 7,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "hally",
    "role": "Coach",
    "age": 32,
    "trophies": 8,
    "majors": 5,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 3,
    "trophies_a": 5,
    "trophies_last_3_years": 8,
    "tactics": 1,
    "development": 1,
    "teamLogo": "/images/spirit-logo.webp"
  },
  {
    "name": "chopper",
    "role": "IGL",
    "age": 29,
    "rating": 0.89,
    "trophies": 9,
    "majors": 11,
    "maps": 1636,
    "team_name": "Spirit",
    "team_rank": 3,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 3,
    "trophies_a": 6,
    "teamLogo": "/images/spirit-logo.webp",
    "is_bench": true
  },
  {
    "name": "Aleksib",
    "role": "IGL",
    "age": 29,
    "rating": 0.88,
    "trophies": 8,
    "majors": 10,
    "maps": 1663,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 1,
    "trophies_a": 7,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "iM",
    "role": "Rifler",
    "age": 26,
    "rating": 1.06,
    "trophies": 6,
    "majors": 7,
    "maps": 1445,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 1,
    "trophies_a": 5,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "b1t",
    "role": "Rifler",
    "age": 23,
    "rating": 1.13,
    "trophies": 15,
    "majors": 9,
    "maps": 1090,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.65,
    "trophies_s": 4,
    "trophies_a": 11,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "w0nderful",
    "role": "AWP",
    "age": 21,
    "rating": 1.11,
    "trophies": 6,
    "majors": 6,
    "maps": 870,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 1,
    "trophies_a": 5,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "makazze",
    "role": "Rifler",
    "age": 19,
    "rating": 1.14,
    "trophies": 2,
    "majors": 2,
    "maps": 594,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "B1ad3",
    "role": "Coach",
    "age": 39,
    "trophies": 16,
    "majors": 11,
    "team_name": "Natus Vincere",
    "team_rank": 4,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 5,
    "trophies_a": 11,
    "trophies_last_3_years": 6,
    "tactics": 3,
    "development": 1,
    "teamLogo": "/images/natus-vincere-logo.webp"
  },
  {
    "name": "FalleN",
    "role": "IGL",
    "age": 35,
    "rating": 0.91,
    "trophies": 18,
    "majors": 19,
    "maps": 2269,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.70,
    "trophies_s": 1,
    "trophies_a": 17,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "yuurih",
    "role": "Rifler",
    "age": 26,
    "rating": 0.99,
    "trophies": 8,
    "majors": 11,
    "maps": 1685,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 8,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "YEKINDAR",
    "role": "Rifler",
    "age": 26,
    "rating": 1.07,
    "trophies": 6,
    "majors": 8,
    "maps": 1763,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.45,
    "trophies_s": 0,
    "trophies_a": 6,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "KSCERATO",
    "role": "Rifler",
    "age": 26,
    "rating": 1.15,
    "trophies": 8,
    "majors": 11,
    "maps": 1592,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.55,
    "trophies_s": 0,
    "trophies_a": 8,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "molodoy",
    "role": "AWP",
    "age": 21,
    "rating": 1.15,
    "trophies": 4,
    "majors": 3,
    "maps": 422,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.60,
    "trophies_s": 0,
    "trophies_a": 4,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "sidde",
    "role": "Coach",
    "age": 29,
    "trophies": 4,
    "majors": 4,
    "team_name": "FURIA",
    "team_rank": 5,
    "region": "SA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 4,
    "trophies_last_3_years": 4,
    "tactics": 1,
    "development": 0,
    "teamLogo": "/images/furia-logo.webp"
  },
  {
    "name": "torzsi",
    "role": "AWP",
    "age": 24,
    "rating": 1.03,
    "trophies": 4,
    "majors": 7,
    "maps": 1123,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 0,
    "trophies_a": 4,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "Spinx",
    "role": "Rifler",
    "age": 25,
    "rating": 1.08,
    "trophies": 8,
    "majors": 9,
    "maps": 1072,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 3,
    "trophies_a": 5,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "jL",
    "role": "Rifler",
    "age": 26,
    "rating": 1.06,
    "trophies": 4,
    "majors": 4,
    "maps": 956,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.60,
    "trophies_s": 1,
    "trophies_a": 3,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "xertioN",
    "role": "IGL",
    "age": 21,
    "rating": 1.14,
    "trophies": 4,
    "majors": 7,
    "maps": 858,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 4,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "xelex",
    "role": "Rifler",
    "age": 18,
    "rating": 1.04,
    "trophies": 0,
    "majors": 1,
    "maps": 298,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "sycrone",
    "role": "Coach",
    "age": 30,
    "trophies": 4,
    "majors": 7,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 4,
    "trophies_last_3_years": 4,
    "tactics": 1,
    "development": 2,
    "teamLogo": "/images/mouz-logo.webp"
  },
  {
    "name": "Brollan",
    "role": "IGL",
    "age": 24,
    "rating": 0.99,
    "trophies": 5,
    "majors": 9,
    "maps": 1609,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 5,
    "teamLogo": "/images/mouz-logo.webp",
    "is_bench": true
  },
  {
    "name": "Jimpphat",
    "role": "Rifler",
    "age": 19,
    "rating": 1.04,
    "trophies": 4,
    "majors": 4,
    "maps": 852,
    "team_name": "MOUZ",
    "team_rank": 6,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 4,
    "teamLogo": "/images/mouz-logo.webp",
    "is_bench": true
  },
  {
    "name": "Jame",
    "role": "AWP+IGL",
    "age": 27,
    "rating": 1.07,
    "trophies": 6,
    "majors": 11,
    "maps": 2006,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.55,
    "trophies_s": 1,
    "trophies_a": 5,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "BELCHONOKK",
    "role": "Rifler",
    "age": 22,
    "rating": 0.94,
    "trophies": 1,
    "majors": 2,
    "maps": 882,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "xiELO",
    "role": "Rifler",
    "age": 20,
    "rating": 0.99,
    "trophies": 1,
    "majors": 2,
    "maps": 759,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "nota",
    "role": "Rifler",
    "age": 19,
    "rating": 0.96,
    "trophies": 1,
    "majors": 2,
    "maps": 613,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "zweih",
    "role": "Rifler",
    "age": 18,
    "rating": 1.07,
    "trophies": 3,
    "majors": 3,
    "maps": 471,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 1,
    "trophies_a": 2,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "dastan",
    "role": "Coach",
    "age": 32,
    "trophies": 6,
    "majors": 9,
    "team_name": "PARIVISION",
    "team_rank": 7,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 1,
    "trophies_a": 5,
    "trophies_last_3_years": 2,
    "tactics": 2,
    "development": 1,
    "teamLogo": "/images/parivision-logo.webp"
  },
  {
    "name": "MAJ3R",
    "role": "IGL",
    "age": 35,
    "rating": 0.93,
    "trophies": 1,
    "majors": 6,
    "maps": 1775,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "XANTARES",
    "role": "Rifler",
    "age": 30,
    "rating": 1.11,
    "trophies": 5,
    "majors": 8,
    "maps": 2516,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.65,
    "trophies_s": 0,
    "trophies_a": 5,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "woxic",
    "role": "AWP",
    "age": 27,
    "rating": 1.06,
    "trophies": 4,
    "majors": 8,
    "maps": 1835,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 4,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "soulfly",
    "role": "Rifler",
    "age": 22,
    "rating": 1.06,
    "trophies": 0,
    "majors": 1,
    "maps": 760,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "Wicadia",
    "role": "Rifler",
    "age": 21,
    "rating": 1.08,
    "trophies": 1,
    "majors": 4,
    "maps": 610,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "Fabre",
    "role": "Coach",
    "age": 36,
    "trophies": 1,
    "majors": 4,
    "team_name": "Aurora",
    "team_rank": 8,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 1,
    "trophies_last_3_years": 1,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/aurora-logo.webp"
  },
  {
    "name": "bLitZ",
    "role": "IGL",
    "age": 24,
    "rating": 0.95,
    "trophies": 2,
    "majors": 8,
    "maps": 947,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "Techno",
    "role": "Rifler",
    "age": 21,
    "rating": 0.94,
    "trophies": 2,
    "majors": 8,
    "maps": 896,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "mzinho",
    "role": "Rifler",
    "age": 18,
    "rating": 1.04,
    "trophies": 2,
    "majors": 5,
    "maps": 594,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "910",
    "role": "AWP",
    "age": 23,
    "rating": 1.12,
    "trophies": 2,
    "majors": 5,
    "maps": 628,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.45,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "cobrazera",
    "role": "Rifler",
    "age": 20,
    "rating": 1.02,
    "trophies": 0,
    "majors": 2,
    "maps": 346,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "maaRaa",
    "role": "Coach",
    "age": 36,
    "trophies": 2,
    "majors": 8,
    "team_name": "The MongolZ",
    "team_rank": 9,
    "region": "AS",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 2,
    "trophies_last_3_years": 2,
    "tactics": 1,
    "development": 1,
    "teamLogo": "/images/mongolz-logo.webp"
  },
  {
    "name": "Hooxi",
    "role": "IGL",
    "age": 31,
    "rating": 0.85,
    "trophies": 3,
    "majors": 6,
    "maps": 1293,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.60,
    "trophies_s": 3,
    "trophies_a": 0,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "phzy",
    "role": "AWP",
    "age": 23,
    "rating": 1.07,
    "trophies": 0,
    "majors": 3,
    "maps": 1133,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "jabbi",
    "role": "Rifler",
    "age": 22,
    "rating": 1.05,
    "trophies": 2,
    "majors": 6,
    "maps": 1415,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "Staehr",
    "role": "Rifler",
    "age": 21,
    "rating": 1.15,
    "trophies": 4,
    "majors": 3,
    "maps": 984,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "ryu",
    "role": "Rifler",
    "age": 21,
    "rating": 1.01,
    "trophies": 0,
    "majors": 1,
    "maps": 718,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "ruggah",
    "role": "Coach",
    "age": 37,
    "trophies": 2,
    "majors": 8,
    "team_name": "Astralis",
    "team_rank": 10,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 2,
    "trophies_last_3_years": 0,
    "tactics": 2,
    "development": 0,
    "teamLogo": "/images/astralis-logo.webp"
  },
  {
    "name": "huNter-",
    "role": "IGL",
    "age": 30,
    "rating": 1.01,
    "trophies": 7,
    "majors": 9,
    "maps": 2125,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 4,
    "trophies_a": 3,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "NertZ",
    "role": "Rifler",
    "age": 26,
    "rating": 1.07,
    "trophies": 1,
    "majors": 6,
    "maps": 952,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "SunPayus",
    "role": "AWP",
    "age": 27,
    "rating": 1.05,
    "trophies": 2,
    "majors": 6,
    "maps": 1001,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "HeavyGod",
    "role": "Rifler",
    "age": 23,
    "rating": 1.16,
    "trophies": 1,
    "majors": 4,
    "maps": 846,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "MATYS",
    "role": "Rifler",
    "age": 24,
    "rating": 1.08,
    "trophies": 1,
    "majors": 3,
    "maps": 1109,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "sAw",
    "role": "Coach",
    "age": 33,
    "trophies": 2,
    "majors": 9,
    "team_name": "G2",
    "team_rank": 11,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 2,
    "trophies_last_3_years": 1,
    "tactics": 1,
    "development": 2,
    "teamLogo": "/images/g2-logo.webp"
  },
  {
    "name": "dem0n",
    "role": "Rifler",
    "age": 18,
    "rating": 1.05,
    "trophies": 1,
    "majors": 1,
    "maps": 712,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "lauNX",
    "role": "Rifler",
    "age": 21,
    "rating": 1.07,
    "trophies": 1,
    "majors": 2,
    "maps": 1095,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "Krabeni",
    "role": "IGL",
    "age": 21,
    "rating": 1.05,
    "trophies": 1,
    "majors": 1,
    "maps": 750,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "cmtry",
    "role": "AWP",
    "age": 18,
    "rating": 0.99,
    "trophies": 1,
    "majors": 1,
    "maps": 599,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "dziugss",
    "role": "Rifler",
    "age": 27,
    "rating": 1.10,
    "trophies": 1,
    "majors": 1,
    "maps": 608,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "coolio",
    "role": "Coach",
    "age": 25,
    "trophies": 1,
    "majors": 1,
    "team_name": "FUT",
    "team_rank": 12,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 1,
    "trophies_last_3_years": 1,
    "tactics": 0,
    "development": 1,
    "teamLogo": "/images/fut-logo.webp"
  },
  {
    "name": "arT",
    "role": "IGL",
    "age": 30,
    "rating": 0.97,
    "trophies": 5,
    "majors": 10,
    "maps": 1730,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 5,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "dumau",
    "role": "Rifler",
    "age": 22,
    "rating": 1.17,
    "trophies": 2,
    "majors": 6,
    "maps": 1247,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "latto",
    "role": "Rifler",
    "age": 23,
    "rating": 1.15,
    "trophies": 2,
    "majors": 6,
    "maps": 1151,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "n1ssim",
    "role": "Rifler",
    "age": 25,
    "rating": 1.01,
    "trophies": 2,
    "majors": 4,
    "maps": 675,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "saadzin",
    "role": "Rifler",
    "age": 22,
    "rating": 1.06,
    "trophies": 2,
    "majors": 3,
    "maps": 751,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "RiVAS",
    "role": "Coach",
    "age": 38,
    "trophies": 0,
    "majors": 0,
    "team_name": "Legacy",
    "team_rank": 13,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/legacy-logo.webp"
  },
  {
    "name": "Snax",
    "role": "IGL",
    "age": 32,
    "rating": 0.89,
    "trophies": 15,
    "majors": 17,
    "maps": 2780,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 1,
    "trophies_a": 14,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "REZ",
    "role": "Rifler",
    "age": 28,
    "rating": 1.15,
    "trophies": 2,
    "majors": 9,
    "maps": 1989,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "Tauson",
    "role": "Rifler",
    "age": 20,
    "rating": 1.05,
    "trophies": 0,
    "majors": 3,
    "maps": 946,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "PR",
    "role": "Rifler",
    "age": 18,
    "rating": 1.06,
    "trophies": 0,
    "majors": 2,
    "maps": 717,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "hypex",
    "role": "AWP",
    "age": 22,
    "rating": 1.06,
    "trophies": 0,
    "majors": 2,
    "maps": 411,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "imd",
    "role": "Coach",
    "age": 29,
    "trophies": 0,
    "majors": 1,
    "team_name": "GamerLegion",
    "team_rank": 14,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/gamerlegion-logo.webp"
  },
  {
    "name": "Boombl4",
    "role": "IGL",
    "age": 27,
    "rating": 0.96,
    "trophies": 10,
    "majors": 10,
    "maps": 1850,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 4,
    "trophies_a": 6,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "s1ren",
    "role": "Rifler",
    "age": 23,
    "rating": 1.06,
    "trophies": 0,
    "majors": 3,
    "maps": 995,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "d1Ledez",
    "role": "Rifler",
    "age": 22,
    "rating": 1.09,
    "trophies": 0,
    "majors": 1,
    "maps": 1089,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "zorte",
    "role": "AWP",
    "age": 28,
    "rating": 1.10,
    "trophies": 0,
    "majors": 4,
    "maps": 1633,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "Magnojez",
    "role": "Rifler",
    "age": 21,
    "rating": 1.21,
    "trophies": 0,
    "majors": 2,
    "maps": 853,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "Fierce",
    "role": "Coach",
    "age": 36,
    "trophies": 0,
    "majors": 6,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/betboom-logo.webp"
  },
  {
    "name": "FL4MUS",
    "role": "Rifler",
    "age": 21,
    "rating": 1.09,
    "trophies": 0,
    "majors": 3,
    "maps": 569,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/betboom-logo.webp",
    "is_bench": true
  },
  {
    "name": "ArtFr0st",
    "role": "AWP",
    "age": 24,
    "rating": 1.14,
    "trophies": 1,
    "majors": 0,
    "maps": 901,
    "team_name": "BetBoom",
    "team_rank": 15,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/betboom-logo.webp",
    "is_bench": true
  },
  {
    "name": "alex666",
    "role": "Rifler",
    "age": 24,
    "rating": 0.99,
    "trophies": 1,
    "majors": 3,
    "maps": 792,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "npl",
    "role": "IGL",
    "age": 20,
    "rating": 1.10,
    "trophies": 0,
    "majors": 4,
    "maps": 906,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "s1zzi",
    "role": "AWP",
    "age": 16,
    "rating": 0.99,
    "trophies": 0,
    "majors": 1,
    "maps": 111,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "kensizor",
    "role": "Rifler",
    "age": 20,
    "rating": 1.03,
    "trophies": 0,
    "majors": 3,
    "maps": 620,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "esenthial",
    "role": "Rifler",
    "age": 20,
    "rating": 1.00,
    "trophies": 0,
    "majors": 3,
    "maps": 648,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "maddened",
    "role": "Coach",
    "age": 25,
    "trophies": 0,
    "majors": 3,
    "team_name": "B8",
    "team_rank": 16,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/b8-logo.webp"
  },
  {
    "name": "LNZ",
    "role": "IGL",
    "age": 23,
    "rating": 1.02,
    "trophies": 1,
    "majors": 3,
    "maps": 1077,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "brnz4n",
    "role": "Rifler",
    "age": 22,
    "rating": 1.00,
    "trophies": 0,
    "majors": 3,
    "maps": 851,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "insani",
    "role": "Rifler",
    "age": 22,
    "rating": 1.25,
    "trophies": 0,
    "majors": 4,
    "maps": 838,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "venomzera",
    "role": "Rifler",
    "age": 21,
    "rating": 1.06,
    "trophies": 0,
    "majors": 2,
    "maps": 933,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "kl1m",
    "role": "AWP",
    "age": 20,
    "rating": 1.22,
    "trophies": 0,
    "majors": 2,
    "maps": 230,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "LETN1",
    "role": "Coach",
    "age": 33,
    "trophies": 0,
    "majors": 1,
    "team_name": "MIBR",
    "team_rank": 17,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/mibr-logo.webp"
  },
  {
    "name": "Gizmy",
    "role": "IGL",
    "age": 22,
    "rating": 0.95,
    "trophies": 0,
    "majors": 1,
    "maps": 838,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "afro",
    "role": "AWP",
    "age": 27,
    "rating": 1.14,
    "trophies": 0,
    "majors": 1,
    "maps": 1365,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "Rainwaker",
    "role": "Rifler",
    "age": 25,
    "rating": 1.12,
    "trophies": 0,
    "majors": 1,
    "maps": 2058,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "AZUWU",
    "role": "Rifler",
    "age": 22,
    "rating": 0.95,
    "trophies": 0,
    "majors": 1,
    "maps": 901,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "Bymas",
    "role": "Rifler",
    "age": 22,
    "rating": 0.98,
    "trophies": 1,
    "majors": 2,
    "maps": 790,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "kakafu",
    "role": "Coach",
    "age": 37,
    "trophies": 0,
    "majors": 4,
    "team_name": "Monte",
    "team_rank": 18,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/monte-logo.webp"
  },
  {
    "name": "Twistzz",
    "role": "IGL",
    "age": 26,
    "rating": 1.10,
    "trophies": 20,
    "majors": 11,
    "maps": 2073,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.65,
    "trophies_s": 3,
    "trophies_a": 17,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "frozen",
    "role": "Rifler",
    "age": 23,
    "rating": 1.18,
    "trophies": 7,
    "majors": 8,
    "maps": 1882,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 0,
    "trophies_a": 7,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "broky",
    "role": "AWP",
    "age": 25,
    "rating": 0.98,
    "trophies": 12,
    "majors": 7,
    "maps": 1388,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 3,
    "trophies_a": 9,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "Neityu",
    "role": "Rifler",
    "age": 20,
    "rating": 1.02,
    "trophies": 0,
    "majors": 0,
    "maps": 813,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "jcobbb",
    "role": "Rifler",
    "age": 22,
    "rating": 0.96,
    "trophies": 0,
    "majors": 1,
    "maps": 383,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "enkay J",
    "role": "Coach",
    "age": 36,
    "trophies": 0,
    "majors": 1,
    "team_name": "FaZe",
    "team_rank": 19,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/faze-logo.webp"
  },
  {
    "name": "Maka",
    "role": "IGL+AWP",
    "age": 28,
    "rating": 1.01,
    "trophies": 0,
    "majors": 3,
    "maps": 2161,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "Lucky",
    "role": "Rifler",
    "age": 28,
    "rating": 1.06,
    "trophies": 0,
    "majors": 5,
    "maps": 2154,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "Graviti",
    "role": "Rifler",
    "age": 22,
    "rating": 0.96,
    "trophies": 0,
    "majors": 3,
    "maps": 841,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "misutaaa",
    "role": "Rifler",
    "age": 23,
    "rating": 1.06,
    "trophies": 2,
    "majors": 2,
    "maps": 1222,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 0,
    "trophies_a": 2,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "Ex3rcice",
    "role": "Rifler",
    "age": 26,
    "rating": 0.98,
    "trophies": 0,
    "majors": 3,
    "maps": 1328,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "wasiNk",
    "role": "Coach",
    "age": 30,
    "trophies": 0,
    "majors": 2,
    "team_name": "3DMAX",
    "team_rank": 20,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/3dmax-logo.webp"
  },
  {
    "name": "max",
    "role": "IGL",
    "age": 27,
    "rating": 0.97,
    "trophies": 0,
    "majors": 3,
    "maps": 1345,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "dgt",
    "role": "Rifler",
    "age": 25,
    "rating": 1.16,
    "trophies": 0,
    "majors": 5,
    "maps": 1107,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "meyern",
    "role": "AWP",
    "age": 23,
    "rating": 1.01,
    "trophies": 0,
    "majors": 1,
    "maps": 1209,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "luchov",
    "role": "Rifler",
    "age": 25,
    "rating": 1.19,
    "trophies": 0,
    "majors": 1,
    "maps": 1027,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "HUASOPEEK",
    "role": "Rifler",
    "age": 23,
    "rating": 1.13,
    "trophies": 0,
    "majors": 1,
    "maps": 643,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "BIT",
    "role": "Coach",
    "age": 35,
    "trophies": 0,
    "majors": 2,
    "team_name": "9z",
    "team_rank": 21,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/9z-logo.webp"
  },
  {
    "name": "biguzera",
    "role": "IGL",
    "age": 29,
    "rating": 0.94,
    "trophies": 0,
    "majors": 7,
    "maps": 1515,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "vsm",
    "role": "Rifler",
    "age": 26,
    "rating": 1.00,
    "trophies": 0,
    "majors": 2,
    "maps": 1229,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "snow",
    "role": "Rifler",
    "age": 19,
    "rating": 1.04,
    "trophies": 0,
    "majors": 4,
    "maps": 808,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "piriajr",
    "role": "Rifler",
    "age": 23,
    "rating": 1.05,
    "trophies": 0,
    "majors": 2,
    "maps": 1011,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "saffee",
    "role": "AWP",
    "age": 31,
    "rating": 1.03,
    "trophies": 0,
    "majors": 7,
    "maps": 954,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "rikz",
    "role": "Coach",
    "age": 35,
    "trophies": 0,
    "majors": 6,
    "team_name": "paiN",
    "team_rank": 22,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/pain-logo.webp"
  },
  {
    "name": "Chr1zN",
    "role": "IGL",
    "age": 19,
    "rating": 0.95,
    "trophies": 0,
    "majors": 2,
    "maps": 1016,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "xfl0ud",
    "role": "Rifler",
    "age": 23,
    "rating": 1.08,
    "trophies": 0,
    "majors": 3,
    "maps": 948,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "nilo",
    "role": "Rifler",
    "age": 21,
    "rating": 1.14,
    "trophies": 0,
    "majors": 1,
    "maps": 985,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "susp",
    "role": "Rifler",
    "age": 21,
    "rating": 1.00,
    "trophies": 0,
    "majors": 3,
    "maps": 715,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "yxngstxr",
    "role": "AWP",
    "age": 21,
    "rating": 1.00,
    "trophies": 0,
    "majors": 2,
    "maps": 634,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "TOBIZ",
    "role": "Coach",
    "age": 31,
    "trophies": 0,
    "majors": 1,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/heroic-logo.webp"
  },
  {
    "name": "Alkaren",
    "role": "AWP",
    "age": 19,
    "rating": 1.06,
    "trophies": 0,
    "majors": 0,
    "maps": 341,
    "team_name": "HEROIC",
    "team_rank": 23,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/heroic-logo.webp",
    "is_bench": true
  },
  {
    "name": "Snappi",
    "role": "IGL",
    "age": 36,
    "rating": 0.88,
    "trophies": 1,
    "majors": 6,
    "maps": 2267,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "sjuush",
    "role": "Rifler",
    "age": 27,
    "rating": 1.01,
    "trophies": 5,
    "majors": 7,
    "maps": 1578,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 5,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "xKacpersky",
    "role": "Rifler",
    "age": 19,
    "rating": 1.15,
    "trophies": 0,
    "majors": 1,
    "maps": 458,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "stavn",
    "role": "Rifler",
    "age": 24,
    "rating": 1.07,
    "trophies": 6,
    "majors": 4,
    "maps": 1578,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 6,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "n0te",
    "role": "AWP",
    "age": 20,
    "rating": 1.05,
    "trophies": 0,
    "majors": 0,
    "maps": 458,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.00,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "Xizt",
    "role": "Coach",
    "age": 35,
    "trophies": 3,
    "majors": 16,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 3,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/nip-logo.webp"
  },
  {
    "name": "ewjerkz",
    "role": "Rifler",
    "age": 25,
    "rating": 1.08,
    "trophies": 0,
    "majors": 2,
    "maps": 458,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nip-logo.webp",
    "is_bench": true
  },
  {
    "name": "cairne",
    "role": "Rifler",
    "age": 23,
    "rating": 1.03,
    "trophies": 0,
    "majors": 0,
    "maps": 458,
    "team_name": "NIP",
    "team_rank": 24,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nip-logo.webp",
    "is_bench": true
  },
  {
    "name": "tabseN",
    "role": "IGL",
    "age": 31,
    "rating": 0.97,
    "trophies": 5,
    "majors": 10,
    "maps": 2837,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.40,
    "trophies_s": 0,
    "trophies_a": 5,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "blameF",
    "role": "Rifler",
    "age": 29,
    "rating": 1.24,
    "trophies": 1,
    "majors": 4,
    "maps": 1695,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.45,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "faveN",
    "role": "Rifler",
    "age": 26,
    "rating": 1.05,
    "trophies": 0,
    "majors": 2,
    "maps": 2185,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "JDC",
    "role": "Rifler",
    "age": 26,
    "rating": 1.13,
    "trophies": 0,
    "majors": 4,
    "maps": 1254,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "gr1ks",
    "role": "AWP",
    "age": 20,
    "rating": 1.12,
    "trophies": 0,
    "majors": 1,
    "maps": 705,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "xenn",
    "role": "Coach",
    "age": 30,
    "trophies": 0,
    "majors": 1,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/big-logo.webp"
  },
  {
    "name": "Krimbo",
    "role": "Rifler",
    "age": 23,
    "rating": 1.09,
    "trophies": 1,
    "majors": 3,
    "maps": 1115,
    "team_name": "BIG",
    "team_rank": 25,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/big-logo.webp",
    "is_bench": true
  },
  {
    "name": "alex",
    "role": "IGL",
    "age": 30,
    "rating": 1.03,
    "trophies": 0,
    "majors": 1,
    "maps": 2061,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "mopoz",
    "role": "Rifler",
    "age": 29,
    "rating": 1.10,
    "trophies": 0,
    "majors": 2,
    "maps": 2001,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "sausol",
    "role": "Rifler",
    "age": 26,
    "rating": 1.07,
    "trophies": 0,
    "majors": 0,
    "maps": 1056,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "dav1g",
    "role": "Rifler",
    "age": 25,
    "rating": 0.98,
    "trophies": 0,
    "majors": 2,
    "maps": 629,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "MartinezSa",
    "role": "AWP",
    "age": 25,
    "rating": 1.09,
    "trophies": 0,
    "majors": 0,
    "maps": 416,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "deLonge",
    "role": "Coach",
    "age": 31,
    "trophies": 0,
    "majors": 1,
    "team_name": "Gentle Mates",
    "team_rank": 26,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/gentle-mates-logo.webp"
  },
  {
    "name": "EliGE",
    "role": "Rifler",
    "age": 28,
    "rating": 1.04,
    "trophies": 11,
    "majors": 17,
    "maps": 2222,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.50,
    "trophies_s": 0,
    "trophies_a": 11,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "NAF",
    "role": "Rifler",
    "age": 28,
    "rating": 1.06,
    "trophies": 13,
    "majors": 14,
    "maps": 2191,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.35,
    "trophies_s": 0,
    "trophies_a": 13,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "malbsMd",
    "role": "Rifler",
    "age": 23,
    "rating": 1.05,
    "trophies": 3,
    "majors": 4,
    "maps": 1261,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 1,
    "trophies_a": 2,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "ultimate",
    "role": "AWP",
    "age": 22,
    "rating": 0.99,
    "trophies": 0,
    "majors": 4,
    "maps": 574,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "siuhy",
    "role": "IGL",
    "age": 23,
    "rating": 0.87,
    "trophies": 3,
    "majors": 7,
    "maps": 1137,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 3,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "flashie",
    "role": "Coach",
    "age": 30,
    "trophies": 0,
    "majors": 2,
    "team_name": "Liquid",
    "team_rank": 27,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/liquid-logo.webp"
  },
  {
    "name": "nitr0",
    "role": "IGL",
    "age": 30,
    "rating": 0.97,
    "trophies": 11,
    "majors": 14,
    "maps": 1943,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 11,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "oSee",
    "role": "AWP",
    "age": 27,
    "rating": 1.03,
    "trophies": 0,
    "majors": 5,
    "maps": 1735,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.20,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "Grim",
    "role": "Rifler",
    "age": 25,
    "rating": 1.09,
    "trophies": 0,
    "majors": 8,
    "maps": 1504,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.25,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "br0",
    "role": "Rifler",
    "age": 24,
    "rating": 1.10,
    "trophies": 1,
    "majors": 3,
    "maps": 851,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 1,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "Sonic",
    "role": "Rifler",
    "age": 27,
    "rating": 1.05,
    "trophies": 0,
    "majors": 4,
    "maps": 1502,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "daps",
    "role": "Coach",
    "age": 32,
    "trophies": 0,
    "majors": 5,
    "team_name": "NRG",
    "team_rank": 28,
    "region": "NA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/nrg-logo.webp"
  },
  {
    "name": "n0rb3r7",
    "role": "Rifler",
    "age": 25,
    "rating": 1.15,
    "trophies": 2,
    "majors": 4,
    "maps": 1639,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.25,
    "trophies_s": 1,
    "trophies_a": 1,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "kade0",
    "role": "Rifler",
    "age": 26,
    "rating": 1.08,
    "trophies": 0,
    "majors": 0,
    "maps": 708,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "mizu",
    "role": "Rifler",
    "age": 22,
    "rating": 1.14,
    "trophies": 0,
    "majors": 0,
    "maps": 492,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "dukefissura",
    "role": "IGL",
    "age": 30,
    "rating": 1.02,
    "trophies": 0,
    "majors": 0,
    "maps": 675,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "frontales",
    "role": "AWP",
    "age": 23,
    "rating": 1.07,
    "trophies": 0,
    "majors": 0,
    "maps": 281,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "mou",
    "role": "Coach",
    "age": 34,
    "trophies": 0,
    "majors": 0,
    "team_name": "HOTU",
    "team_rank": 29,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/hotu-logo.webp"
  },
  {
    "name": "twist",
    "role": "IGL",
    "age": 31,
    "rating": 1.02,
    "trophies": 0,
    "majors": 5,
    "maps": 2648,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "eraa",
    "role": "AWP",
    "age": 24,
    "rating": 1.17,
    "trophies": 0,
    "majors": 0,
    "maps": 1531,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "upE",
    "role": "Rifler",
    "age": 22,
    "rating": 0.98,
    "trophies": 0,
    "majors": 0,
    "maps": 694,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "avid",
    "role": "Rifler",
    "age": 22,
    "rating": 1.04,
    "trophies": 0,
    "majors": 0,
    "maps": 1279,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "Mail09",
    "role": "Rifler",
    "age": 17,
    "rating": 1.19,
    "trophies": 0,
    "majors": 0,
    "maps": 349,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "Hawk",
    "role": "Coach",
    "age": 29,
    "trophies": 0,
    "majors": 0,
    "team_name": "Alliance",
    "team_rank": 30,
    "region": "EU",
    "popularity": 1.00,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/alliance-logo.webp"
  },
  {
    "name": "slaxz-",
    "role": "AWP",
    "age": 27,
    "rating": 1.11,
    "trophies": 0,
    "majors": 4,
    "maps": 1810,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "Swisher",
    "role": "Rifler",
    "age": 27,
    "rating": 1.11,
    "trophies": 0,
    "majors": 3,
    "maps": 1521,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "s1n",
    "role": "IGL",
    "age": 27,
    "rating": 1.01,
    "trophies": 0,
    "majors": 4,
    "maps": 1039,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "JBa",
    "role": "Rifler",
    "age": 22,
    "rating": 1.04,
    "trophies": 0,
    "majors": 3,
    "maps": 706,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "Lake",
    "role": "Rifler",
    "age": 21,
    "rating": 1.12,
    "trophies": 0,
    "majors": 3,
    "maps": 557,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "dephh",
    "role": "Coach",
    "age": 34,
    "trophies": 0,
    "majors": 3,
    "team_name": "M80",
    "team_rank": 31,
    "region": "NA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/m80-logo.webp"
  },
  {
    "name": "beastik",
    "role": "IGL",
    "age": 28,
    "rating": 1.03,
    "trophies": 0,
    "majors": 1,
    "maps": 2000,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "SHOCK",
    "role": "Rifler",
    "age": 25,
    "rating": 1.03,
    "trophies": 0,
    "majors": 1,
    "maps": 2004,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "MoDo",
    "role": "AWP",
    "age": 21,
    "rating": 1.09,
    "trophies": 0,
    "majors": 1,
    "maps": 846,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "kisserek",
    "role": "Rifler",
    "age": 23,
    "rating": 1.07,
    "trophies": 0,
    "majors": 1,
    "maps": 600,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "stressarN",
    "role": "Rifler",
    "age": 23,
    "rating": 1.08,
    "trophies": 0,
    "majors": 1,
    "maps": 311,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "Bfull",
    "role": "Coach",
    "age": 34,
    "trophies": 0,
    "majors": 1,
    "team_name": "SINNERS",
    "team_rank": 32,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/sinners-logo.webp"
  },
  {
    "name": "gafolo",
    "role": "IGL",
    "age": 24,
    "rating": 0.98,
    "trophies": 0,
    "majors": 1,
    "maps": 1181,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "koala",
    "role": "Rifler",
    "age": 21,
    "rating": 1.13,
    "trophies": 0,
    "majors": 1,
    "maps": 930,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "maxxkor",
    "role": "Rifler",
    "age": 23,
    "rating": 1.04,
    "trophies": 0,
    "majors": 1,
    "maps": 520,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "rdnzao",
    "role": "Rifler",
    "age": 23,
    "rating": 1.04,
    "trophies": 0,
    "majors": 1,
    "maps": 983,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "doc",
    "role": "AWP",
    "age": 23,
    "rating": 1.11,
    "trophies": 0,
    "majors": 1,
    "maps": 903,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "coachi",
    "role": "Coach",
    "age": 39,
    "trophies": 0,
    "majors": 2,
    "team_name": "Sharks",
    "team_rank": 33,
    "region": "SA",
    "popularity": 1.00,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/sharks-logo.webp"
  },
  {
    "name": "JW",
    "role": "AWP",
    "age": 33,
    "rating": 0.94,
    "trophies": 23,
    "majors": 14,
    "maps": 3075,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.30,
    "trophies_s": 5,
    "trophies_a": 18,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "maxster",
    "role": "Rifler",
    "age": 21,
    "rating": 1.11,
    "trophies": 0,
    "majors": 0,
    "maps": 758,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "Ro1f",
    "role": "Rifler",
    "age": 21,
    "rating": 1.03,
    "trophies": 0,
    "majors": 0,
    "maps": 1221,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "bobeksde",
    "role": "IGL",
    "age": 22,
    "rating": 1.04,
    "trophies": 0,
    "majors": 0,
    "maps": 1284,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "dex",
    "role": "Rifler",
    "age": 25,
    "rating": 0.95,
    "trophies": 0,
    "majors": 0,
    "maps": 566,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "pita",
    "role": "Coach",
    "age": 35,
    "trophies": 2,
    "majors": 8,
    "team_name": "EYEBALLERS",
    "team_rank": 34,
    "region": "EU",
    "popularity": 1.07,
    "trophies_s": 1,
    "trophies_a": 1,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/eyeballers-logo.webp"
  },
  {
    "name": "cptkurtka023",
    "role": "Rifler",
    "age": 26,
    "rating": 1.05,
    "trophies": 0,
    "majors": 0,
    "maps": 1037,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  },
  {
    "name": "onic",
    "role": "IGL",
    "age": 21,
    "rating": 0.96,
    "trophies": 0,
    "majors": 0,
    "maps": 473,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  },
  {
    "name": "zeRRoFIX",
    "role": "Rifler",
    "age": 19,
    "rating": 1.02,
    "trophies": 0,
    "majors": 1,
    "maps": 682,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.10,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  },
  {
    "name": "headtr1ck",
    "role": "AWP",
    "age": 22,
    "rating": 1.07,
    "trophies": 0,
    "majors": 3,
    "maps": 865,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.15,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  },
  {
    "name": "Dawy",
    "role": "Rifler",
    "age": 18,
    "rating": 1.14,
    "trophies": 0,
    "majors": 0,
    "maps": 464,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.05,
    "trophies_s": 0,
    "trophies_a": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  },
  {
    "name": "jR",
    "role": "Coach",
    "age": 32,
    "trophies": 0,
    "majors": 0,
    "team_name": "Inner Circle",
    "team_rank": 35,
    "region": "EU",
    "popularity": 1.00,
    "trophies_s": 0,
    "trophies_a": 0,
    "trophies_last_3_years": 0,
    "tactics": 0,
    "development": 0,
    "teamLogo": "/images/inner-circle-logo.webp"
  }
]